name: Tests

# Trigger for a new workflow
on:
  push:
    paths-ignore:
      - '**.md'
      - '.ipynb'

# What is done in the workflow
jobs:
  tests:  # Job name
    runs-on: ubuntu-latest

    steps:
#      Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

#      Step 2: Setup python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

#      Step 3: Install deps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#      Step 4: run tests
      - name: Run pytest
        env:
          CHALLENGE_USERNAME: ${{ secrets.CHALLENGE_USERNAME }}
          CHALLENGE_PWD: ${{ secrets.CHALLENGE_PWD }}
        run: |
          echo Display username: $CHALLENGE_USERNAME
          pytest --cov -s
